spring.application.name=x6-order
springdoc.swagger-ui.path=/swagger-ui
spring.datasource.url=jdbc:postgresql://localhost:5433/x6_order
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.change-log=/db/changelog/db.changelog-master.yaml
server.port=8082