spring.application.name=x6-order
springdoc.swagger-ui.path=/swagger-ui
spring.datasource.url=jdbc:postgresql://localhost:5433/x6_order
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.change-log=/db/changelog/db.changelog-master.yaml
server.port=8082
spring.rabbitmq.host: localhost
spring.rabbitmq.port: 5672
spring.rabbitmq.username: guest
spring.rabbitmq.password: guest
spring.rabbitmq.virtual-host: x6_vhost
app.rabbitmq.exchange: x6.exchange
app.rabbitmq.queue: x6.order.queue